version: '3'
services:
  server:
    build:
      context: ./server
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_TIME_ZONE=${TIME_ZONE}
    ports:
      - "8080:8080"

  web:
    build:
      context: ./web
    ports:
      - "5173:5173"
    depends_on:
      - server